---
title: "Compute Impulse Response Functions to Structural Shocks using **bayesianVARs**"
author: Stefan Haan^[University of Klagenfurt, mailto:sthaan@edu.aau.at]
output: pdf_document
header-includes:
- \usepackage{physics}
bibliography: irfs.bib
reference-section-title: References
vignette: >
  %\VignetteIndexEntry{Compute Impulse Response Functions to Structural Shocks using **bayesianVARs**}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

# Introduction

The structural $\mathrm{VAR}(p)$ model^[We suppress the intercept of the equation.] assumes the observations $\{y_t\}$ are generated by the process
\begin{equation*}
	y_t' B_0 = y_{t-1}' B_1 + \dots + y_{t-p}' B_p + \omega_t'.
\end{equation*}
The components of $\omega_t$ are required to be uncorrelated (i.e., the variance-covariance matrix $\Sigma_{\omega}$ is a diagonal matrix) and referred to as _structural shocks_.

The model parameter $B_0$ is not identified. The model deserves to be called "structural", only if $B_0$ reflects the instantaneous causal relationships between the variables. Theoretical considerations are used to place restrictions on the entries of $B_0$ [@luetkepohl2005, Section 10.2.2]. Following [@rubioramirez2010], in order to identify $B_0$, we allow the user to specify identifying zero and sign restrictions for several transformations of the structural parameters:

- $B_0$ itself,
- the contemporaneous effects $\mathrm{IR}_0 := B_0'^{-1}$,
- the structural coefficients $B_1, B_2, \dots, B_p$, and
- the long-run effects (sum of the impulse responses over all horizons $h$)
\begin{equation*}
\mathrm{IR}_\infty := \qty(B_0' - \sum_{l=1}^{p} B_l' )^{-1}.
\end{equation*}

An _impulse response function_ describes the effects of an shock to the system over time.
Intuitively, IRFs answer the question: "What is the effect of a shock $\varepsilon_t$ hitting the system at time $t$ on
$y_{t+h}$ for $h = 1,2,\dots$, given that no other shocks hit the system?" [@koop1996].
Formally, we define IRFs as the Jacobian
\begin{equation*}
	\Theta_h := \pdv{y_{t+h}}{\omega_t'}
\end{equation*}

If the (homoskedastic) factor model is used, we define
