# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bvar_cpp <- function(Y, X, M, T, K, draws, burnin, intercept, priorIntercept, PHI, PHI0, priorPHI_in, priorL_in, L, SV, priorHomoscedastic, sv_spec, h, sv_para, i_mat, i_vec, progressbar) {
    .Call(`_bayesianVARs_bvar_cpp`, Y, X, M, T, K, draws, burnin, intercept, priorIntercept, PHI, PHI0, priorPHI_in, priorL_in, L, SV, priorHomoscedastic, sv_spec, h, sv_para, i_mat, i_vec, progressbar)
}

#' Draw from generalized inverse Gaussian
#'
#' Vectorized version of \code{\link[GIGrvg]{rgig}}
#'
#' @param n A single integer indicating the number of draws to generate.
#' @param lambda vector of shape parameters.
#' @param chi vector of shape/scale parameters. Must be nonnegative for positive lambdas and positive else.
#' @param psi vector of shape/scale parameters. Must be nonnegative for negative lambdas and positive else.
#'
#' @export
my_gig <- function(n, lambda, chi, psi) {
    .Call(`_bayesianVARs_my_gig`, n, lambda, chi, psi)
}

draw_PHI <- function(PHI, PHI_prior, Y, X, L, d, V_i, K, M) {
    .Call(`_bayesianVARs_draw_PHI`, PHI, PHI_prior, Y, X, L, d, V_i, K, M)
}

draw_L <- function(Ytilde, V_i, d) {
    .Call(`_bayesianVARs_draw_L`, Ytilde, V_i, d)
}

